version: "3.9"

services:
    kafka2:
        image: confluentinc/cp-kafka:latest
        volumes:
            - kafkavol:/kafka-data 
        ports: 
            - "9093:9093"
        environment:
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://bddst-g04-Node3:9092
        - KAFKA_LISTENERS=PLAINTEXT://bddst-g04-Node3:9092
        - KAFKA_ZOOKEEPER_CONNECT=bddst-g04-Node1.uvm.sdu.dk:2181
        - KAFKA_BROKER_ID=2
        - BOOTSTRAP_SERVERS=bddst-g04-Node2:9091,bddst-g04-Node3:9092
        - ZOOKEEPER=bddst-g04-Node1.uvm.sdu.dk:2181
        restart: unless-stopped

volumes:
    kafkavol:
