version: "3.9"

services:
    kafka2:
        image: confluentinc/cp-kafka:latest
        volumes:
            - kafkavol:/kafka-data 
        ports: 
            - "9093:9093"
        environment:
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092
        - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_BROKER_ID=2
        - BOOTSTRAP_SERVERS=kafka1:9091,kafka2:9092
        - ZOOKEEPER=zookeeper:2181
        restart: unless-stopped

volumes:
    kafkavol:
