version: "3.3"

services:
    kafka1:
        image: confluentinc/cp-kafka:latest
        volumes:
        - kafkavol:/kafka-data 
        ports: 
        - "9091:9091"
        environment:
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://bddst-g04-Node2:9091
        - KAFKA_LISTENERS=PLAINTEXT://bddst-g04-Node2:9091
        - KAFKA_ZOOKEEPER_CONNECT=bddst-g04-Node1.uvm.sdu.dk:2181
        - KAFKA_BROKER_ID=1
        - BOOTSTRAP_SERVERS=bddst-g04-Node2:9091,bddst-g04-Node3:9092
        - ZOOKEEPER=bddst-g04-Node1.uvm.sdu.dk:2181
        restart: unless-stopped

    kowl:
        image: quay.io/cloudhut/kowl:master
        ports: 
            - "8080:8080"
        restart: unless-stopped
        environment:
            KAFKA_BROKERS: bddst-g04-Node2:9091,bddst-g04-Node3:9092

volumes:
    kafkavol:

