version: "3.3"

services:
    kafka1:
        image: confluentinc/cp-kafka:latest
        volumes:
        - kafkavol:/kafka-data 
        ports: 
        - "9091:9091"
        environment:
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9091
        - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9091
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_BROKER_ID=1
        - BOOTSTRAP_SERVERS=kafka1:9091,kafka2:9092
        - ZOOKEEPER=zookeeper:2181
        restart: unless-stopped

    kowl:
        image: quay.io/cloudhut/kowl:master
        ports: 
            - "8080:8080"
        restart: unless-stopped
        environment:
            KAFKA_BROKERS: kafka1:9091,kafka2:9092

volumes:
    kafkavol:

