version: '3'
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=bigdata
    env_file:
      - ./hadoop.env
    ports:
      - "50070:50070"
      - "8020:8020"
volumes:
  namenode:
